# -*- coding: utf-8 -*-
"""파이썬입문.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dzDMaF52DmdPBlGK538pN7QAYi3a4y1U
"""

print('hello')

print('안녕하세요.', end=' ')
print('저는 홍길동입니다.')

#  ctrl + / = 주석 (python, R) // = java
# 입력: 데이터를 가지고 와야감.
# 처리: 적절한 처리
# 출력: 처리한 결과를 내보내는 일 (모니터, 파일, DB저장, 네트워크 전송)

name = input('이름을 입력하세요 >> ') #간단한 처리(기호를 씀): 연산=> 연산자
# = :대입연산자

print(name)

age = input('나이를 입력하세요 >> ')
print(age)

location = "신촌"

number = 2 #숫자는 연산을 해야만 정수가 된다.

height = 195.5

food_lunch = True # 파이썬은 대소문자구분,카멜표기법(JAVA),스네이크표기법(python)

age2 = input('나이 입력>> ') 
# 컴퓨터에서 입력한 데이터는 타입을 무조건 스트링으로 인식
#스트링을 정수로 바꾸어쓰는(강제 casting) 결정은 프로그래머가 한다.
print('내년 나이는',int(age2) + 1)

# 두수를 입력을 받아서, 사칙연산을 해보세요

num1 = 33 
num2 = 4
print(num1 + num2) # 더하기 연산자
print(num1 * num2)
print(num1 / num2)
print(num1 //num2)

me = '커피'
me2 = '우유'
print(me + me2) #결합 연사자

price = 1000

print(me + '가격은 ' + str(price) + '원입니다.')

coffee = int(5000)
count = int(input('커피 잔의 개수는? '))
sum = coffee * count #변수 (저장공간, 저장공간이름=> 변수명)
if sum >= int(20000):
  print('총 가격은', sum - int(2000))
else:
  print('총 가격은', sum)



money = input('1년 만기 정기 예금을 얼마나 예치하시겠습니까? ')
plus = int(money) / 10
all = int(money) + int(plus)
print('원금이',str(money)+'원이시군요..!')
print('이자는', str(int(plus))+'원입니다.')
print('원리합계는', str(all)+'원입니다.')

English = input('영어점수 입력: ')
Korean = input('국어점수 입력: ')
Math = input('수학점수 입력: ')
sum = (int(Math) + int(Korean) + int(English))
print('세 과목의 합은', str(8sum) + '점')
Average = int(sum / 3)
print('세 과목의 평균은', str(Average) + '점')

now = input('지금은 몇 시 입니까? ')
if int(now) <= 12:
  print('점심 전입니다.')
else:
  print('점심 후입니다.')

ID = input('로그인 할 ID를 입력해주세요.')
if ID == 'root':
  print('로그인 되었습니다.')
else:
  print('로그인 되지 않았습니다.')

sticker = input('스티커 갯수? ')
sprice = 1000
bookmark = input('책갈피 갯수? ')
bprice = 2500
member = input('우수회원이라면 (O 작성)')
sum = (int(sticker)*sprice +int(bookmark)*bprice)
if member == 'O':
  print('총',str(int(sum*0.9))+'원입니다.')
else:
  print ('총',str(sum)+'원입니다.')